-- MINI CHALLENGE-- 
-- USE College;
-- CREATE TABLE COURCE (cOURCE_ID INT PRIMARY KEY, COURCE_NAME VARCHAR(50))
 -- INSERT INTO COURCE (COURCE_ID, COURCE_NAME)
-- VALUES(1,"MCA"),
-- (2,"MSC"),
-- (3,"B.TECH")
-- VALUE (4,"CS");
SELECT * FROM COURCE